# yml 파일 설정인데 저는 application.properties설정이 편해서 기록만 남겨둬요
# 확장자변경하고 application.properties 파일 확장자 변경해서 못읽게 하면 돼요

# 포트 설정
server:
  port: 9999
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# MySQL
spring:
  # datasource
  datasource:
    url: jdbc:mysql://localhost:3306/coala?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: coala
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: coala1080@gmail.com
    password: iwcwfcgwtoszgmvp
    smtp:
      auth: true
      timeout: 5000
      starttls:
        enable: true

  # Jpa
  jpa:
    show-sql: true

    # Hibernate
    database: mysql
    hibernate:
      # 서버 실행 시 DB초기화 X
      ddl-auto: update
      # camelcase 설정
      strategy: org.hibernate.cfg.ImprovedNamingStrategy
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # ddl-auto 사용 여부 설정
    generate-ddl: true
    # SQL문 로그 출력
    properties:
      hibernate:
        format_sql: true
      # LazyInitializationException 방지
      enable_lazy_load_no_trans: true

# H2 세팅은 필요시 추가하는걸로...
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.jpa.show-sql=true
#spring.hibernate.ddl-auto=none

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret:
    key : 7J2064W467Kg7J207IWY7Lqg7ZSE7IiY6rCV7IOd67aE65Ok7ZmU7J207YyF7ZWY7IS47JqU7KKL7J2A7ZqM7IKs7JeQ66qo65GQ7Leo7JeF7ISx6rO17ZWY7Iuk6rGw652866+/7Iq164uI64uk65287J2067iM7IS47IWY65Ok7Ja07KO87IWU7ISc6rCQ7IKs7ZWp64uI64uk64+E7JuA7J2065CY7JeI7Jy866m07KKL6rKg7Iq164uI64uk
  token-validity-in-seconds: 86400	# 초